-- Create user_challenges table
create table if not exists public.user_challenges (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  challenge_id text not null, -- matches the 'daily' or 'weekly' ID generated by logic
  joined_at timestamptz default now(),
  completed boolean default false,
  progress integer default 0,
  unique(user_id, challenge_id)
);

-- Enable RLS
alter table public.user_challenges enable row level security;

-- Policies
create policy "Users can view their own challenges"
  on public.user_challenges for select
  using (auth.uid() = user_id);

create policy "Users can join challenges"
  on public.user_challenges for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own challenges"
  on public.user_challenges for update
  using (auth.uid() = user_id);
